spring.application.name=samplePJ

spring.thymeleaf.mode=HTML

#Postgres接続先設定 (5/21ﾊｰﾄﾞｺｰﾄﾞ修正）
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/todo_app
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}


#ログレベル
logging.level.sample.*=DEBUG

#セッション有効期限設定
server.servlet.session.timeout=1d


#JPA

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Tokyo
spring.jpa.open-in-view=false